# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67d27e92baf6cf711c4cb9779f6116469acbcf9fbd05d920845d9d17251fff75d51481b01b868e9da9d62eb91e816417b971ddb88c138f640ae96de99bb753e8

test:
  secret_key_base: 7e0b9724133ed837dfb0065d798f1d15be3b62420acbe4659bd95c097a84373fb343a490ce4598394a28e2daff6bdecf972051c73dc6fb046e69f322f574ee24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
